### ISSUE TITLE
Support for Mutations / InputObjectTypes

### ISSUE THREAD

**Issue by alexhafner** [graphql-python/graphene-pydantic#19]
Hi there!

Are there any plans to extend the graphene-pydantic magic to Graphene Mutations, in particular InputObjectTypes? It would be excellent to be able to validate Mutation arguments against Pydantic Models.

**Comment by necaris** [comment]
Hi @alexhafner -- sorry for the delay responding! We don't _currently_ have plans to extend this further, as it's not a use case that we have, but we'd love to help you with a pull request!

**Comment by alexhafner** [comment]
Thank you Rami, I appreciate the feedback! It will be a while before we get to that point, but great to know that you are open for a pull request on that.

**Comment by necaris** [comment]
Closed by #29

**Comment by necaris** [comment]
@alexhafner note that we have support for these now in the [latest release on PyPI](https://pypi.org/project/graphene-pydantic/)
