### ISSUE TITLE
Great work on the package

### ISSUE THREAD

**Issue by syrusakbary** [graphql-python/graphene-pydantic#28]
Hi team!

I think this package could be a great addition to the GraphQL-Python organization.
Let me know if you would be interested in adding this repo to the org! ❤️

**Comment by necaris** [comment]
@syrusakbary thanks! This was developed at https://github.com/upsidetravel so I don't know how amenable they would be to that -- @jaygorrell do you happen to know who to check with about that sort of thing?

**Comment by jaygorrell** [comment]
Hey @syrusakbary and @necaris, we can do this. I'll go ahead and initiate it.

**Comment by jaygorrell** [comment]
Looks like I may need to be a member temporarily. Is that possible?
>You don’t have the permission to create public repositories on graphql-python

**Comment by syrusakbary** [comment]
> Looks like I may need to be a member temporarily. Is that possible?

Of course.
I’ll add both of you as members of the org.

It will be great if you can join the slack channel as well 🙂

**Comment by syrusakbary** [comment]
Done. You should have received the invite.

Here are some instructions for transfer of the repo:
https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-organization

Excited for having you as part of the team! 🤗

**Comment by jaygorrell** [comment]
Thanks @syrusakbary and done! I am not personally an active participant of the project but @necaris and @dantheman39 would be great options if they have interest.

**Comment by necaris** [comment]
Thanks for sorting this out @jaygorrell !

**Comment by dantheman39** [comment]
I would be interested, thanks @syrusakbary @jaygorrell and @necaris !

**Comment by syrusakbary** [comment]
Just invited you @dantheman39. Closing the issue :)
