### ISSUE TITLE
support for V3?

### ISSUE THREAD

**Issue by hyusetiawan** [graphql-python/graphene-pydantic#36]
looks like v3 is not supported yet, because it's throwing errors during installation

**Comment by necaris** [comment]
@hyusetiawan that's right, I'm afraid we don't support graphene 3.x yet -- see https://github.com/graphql-python/graphene-pydantic/blob/master/pyproject.toml#L24 for the supported versions of `graphene`. If you'd like to help us add support for it, we would welcome your PR!

**Comment by necaris** [comment]
Implemented by #45!
