### ISSUE TITLE
json string support?

### ISSUE THREAD

**Issue by hyusetiawan** [graphql-python/graphene-pydantic#37]
pydantic has support for Json field, i think that maps directly to https://docs.graphene-python.org/en/latest/_modules/graphene/types/json/ of graphene?

**Comment by necaris** [comment]
@hyusetiawan it's not clear to me which JSON field support you mean in Pydantic? Especially since this is something the GraphQL spec specifically discourages people from using, I'm not keen to add support for it unless someone has a clear need for it.

**Comment by necaris** [comment]
Since this hasn't been active in >3 months, I'm closing it; please reopen if you have more comments!

**Comment by eplatonoff** [comment]
@necaris We have a dynamic survey definition schema in one field beside other data in the model. 
So I can try to implement the PR for JSON support if you don't mind.

**Comment by necaris** [comment]
Please do, I'd love to see what you are thinking.

Eugene Platonov ***@***.***> writes:

> @necaris We have a dynamic survey definition schema in one field beside other data in the model.
> So I can try to implement the PR for JSON support if you don't mind.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.


--
Rami Chowdhury
A mind all logic is like a knife all blade - it makes the hand bleed that uses it.
  -- Rabindranath Tagore
