### ISSUE TITLE
Correct handling of python reserved keywords

### ISSUE THREAD

**Issue by MaximZemskov** [graphql-python/graphene-pydantic#38]
Hey.

Is there a way to handle reserved keywords in schema?

Pydantic model that works fine:

```python
class Model(BaseModel):
    class_: str

    class Config:
        fields = {
            'class_': 'class'
        }
```

But with this model, graphene don't see field named `class`. Only `class_`.

**Comment by necaris** [comment]
@MaximZemskov Yep, right now `graphene-pydantic` doesn't correctly account for the `alias` value on a Field; since this might involve changing the way attributes are looked up, it might be a significant change. Would you be interested in helping with a pull request?

**Comment by MaximZemskov** [comment]
Yeah, I could try

**Comment by necaris** [comment]
@MaximZemskov any of us would be very happy to help you with anything you need :smile:

**Comment by MaximZemskov** [comment]
Thanks. Will have a look at the weekend

**Comment by conao3** [comment]
@MaximZemskov 
FYI: I created PR for this issue. please test its branch and feel free to comment.
