### ISSUE TITLE
How do we indicate that a List is made of non-null elements?

### ISSUE THREAD

**Issue by CharlesW95** [graphql-python/graphene-pydantic#47]
Right now, when my pydantic model looks like the following:
```
class MyClassModel(BaseModel):
    myList: List[str]
```
and my graphene model looks like this:

```
class MyClassType(PydanticObjectType):
    class Meta:
        model = MyClassModel
        fields = ("myList")
```

the GraphQL schema output for this field looks like this:

```
myList: [String]!
```

This means that introspection in TypeScript interprets each element in the List as a `Maybe<String>` instead of a `String`. What can I do here to ensure that the type is `myList: [String!]!`?

Thanks!

**Comment by daviddaskell** [comment]
Just reading the source code, I don't think this is currently possible without manually overriding, i.e.

```
class MyClassType(PydanticObjectType):
    class Meta:
        model = MyClassModel
    myList = graphene.List(graphene.NonNull(String), required=True)
```

I haven't tested this, but I think the fix would be [here](https://github.com/graphql-python/graphene-pydantic/blob/master/graphene_pydantic/converters.py#L164) to replace:

```
        return List(graphene_type)
```

with

```
        if not field.sub_fields[0].allow_none:
                graphene_type = graphene.NonNull(graphene_type)
        return List(graphene_type)
```

**Comment by CharlesW95** [comment]
@daviddaskell Thank you! Only need this in one case so going to use the manual override for now.
