### ISSUE TITLE
Pydantic not on latest version

### ISSUE THREAD

**Issue by JosXa** [graphql-python/graphene-pydantic#53]
These lines:

https://github.com/graphql-python/graphene-pydantic/blob/master/pyproject.toml#L23-L25

Make it sound as if the library should be supporting the "latest" Pydantic version(s). Shouldn't that be <**=** or ~ 1.7 then in order to include `1.7.3` (which is the latest at the moment)?
For this reason I had to downgrade pydantic in my project. Are there issues with using semver to stay under the same minor?

**Comment by lovetoburnswhen** [comment]
Any update? This breaks compatibility with a ton of other pydantic libraries

**Comment by necaris** [comment]
Closed by #61
