### ISSUE TITLE
Release a version with changes from: Make it graphene 2 compatible

### ISSUE THREAD

**Issue by terminalkitten** [graphql-python/graphene-pydantic#76]
Hi, is there any plans to release a PyPi version with the changes from the following PR: https://github.com/graphql-python/graphene-pydantic/pull/71?

I saw there where some issues with this PR, but they where resolved. If there are more concerns, is there anyway I could help?

**Comment by necaris** [comment]
New version published at https://pypi.org/project/graphene-pydantic/0.4.0/ with those changes -- thank you for bringing this up! If you could 👍🏽 the associated PR that would be helpful :smile:

**Comment by terminalkitten** [comment]
Great news, thanks so much. I will check the PR.
