### ISSUE TITLE
No support for pydantic-2

### ISSUE THREAD

**Issue by stabacco** [graphql-python/graphene-pydantic#87]
It has been released, with huge performance boosts: 

https://docs.pydantic.dev/2.0/migration/

**Comment by necaris** [comment]
Unfortunately neither of the current maintainers is using FastAPI on a regular basis currently, so we don't have a lot of time to port things. We'd be glad to accept and help with any potential PRs, though!

**Comment by xalteropsx** [comment]
@necaris isnt django also uses ninja api which use pydantic v2 as well

**Comment by xalteropsx** [comment]
@necaris i able to solved it do i share u the code ? it just 7line

**Comment by necaris** [comment]
@xalteropsx yes, please share the code! We'd be very happy to accept a PR.

**Comment by xalteropsx** [comment]
give me 1-2day just gonna complete some office work then i will do it by taking pr else i will share u it

**Comment by neonarc4** [comment]
> @xalteropsx yes, please share the code! We'd be very happy to accept a PR.

class UserType(graphene.ObjectType):
    username = graphene.String()
    family_name = graphene.String()
    password_hash = graphene.String()

class UpdateUserMutation(graphene.Mutation):
    class Arguments:
        id = graphene.Int(required=True)
        user_gp = graphene.Argument(UserType)

    user = graphene.Field(user_g)

    def mutate(self, info, id: int, user_gp):

 what is the mistake here ?
raise cls(f"{self.name} fields cannot be resolved. {error}") from error
TypeError: Mutation fields cannot be resolved. Argument type must be a GraphQL input type.

even i tried inputobjecttype getting this warning TypeError: Mutation fields cannot be resolved. Expected Graphene type, but received: InputObjectType.

@necaris any suggestion ?

**Comment by xalteropsx** [comment]
@necaris i read ur library is not supported properly pydantic v2 as u can see type is now rename to annoatation and alias to fieldname  here how  i manage to make it work 


```py

> @xalteropsx yes, please share the code! We'd be very happy to accept a PR.

@necaris i take a look alot but i found it really hard cause alot of thing not yet docs on pydantic migration 


but here some example 

```py

def Pydantic_Graphene(model, exclude_fields=None):
    if exclude_fields is None:
        exclude_fields = []

    fields = {}
    _id = True
    for field_name, field in model.model_fields.items():
        if field_name not in exclude_fields:
            if field.annotation == str or field.annotation == Optional[str]:
                field_type = String
            elif field.annotation == int or field.annotation == Optional[int]:
                field_type = Int
            elif field.annotation == float or field.annotation == Optional[float]:
                field_type = Float
            elif field.annotation == bool or field.annotation == Optional[bool]:
                field_type = Boolean
            elif field.annotation == List[str] or field.annotation == Optional[List[str]]:
                field_type = List(String)
            elif field.annotation == List[int] or field.annotation == Optional[List[int]]:
                field_type = List(Int)
            elif field.annotation == List[float] or field.annotation == Optional[List[float]]:
                field_type = List(Float)
            elif field.annotation == List[bool] or field.annotation == Optional[List[bool]]:
                field_type = List(Boolean)
            
            fields[field_name] = field_type(required=field.is_required)

    return type(model.__name__ + 'ObjectType', (ObjectType,), fields)
```
UserObjectType = Pydantic_Graphene(User_Pydantic)

**Comment by xalteropsx** [comment]
![image](https://github.com/graphql-python/graphene-pydantic/assets/103671642/da4f7a9c-780b-46c6-b8ae-bde9c028f61e)

**Comment by abhinand-c** [comment]
@necaris We're working on bringing Pydantic V2 to graphene-pydantic, and do have a working implementation but had to drop support for Pydantic V1 (Reducing backward compatibility).

@mak626 can throw more light on our progress.

**Comment by mak626** [comment]
> @necaris We're working on bringing Pydantic V2 to graphene-pydantic, and do have a working implementation but had to drop support for Pydantic V1 (Reducing backward compatibility).
> 
> @mak626 can throw more light on our progress.

Here is our test release supporting pydantic v2 
[v0.5.0-alpha.2]( https://github.com/strollby/graphene-pydantic/releases/tag/v0.5.0-alpha.2)

**Changelog**
- Added support for pydantic v2
   - Change removed `ModelField` -> `FieldInfo` 
   - `pydantic.parse_obj_as(FooBar, data["listFooBars"])` was changed to new syntax `TypeAdapter(FooBar).validate_python(data["createFooBar"])`
- Dropped support for pydantic v1 completely.
- Support for python11 Union using pipe syntax
- Added support for bson `ObjectId` -> `graphene.ID`
- Added support for `dict` -> `JSONString`


Pydantic V2 also changed the way we define fields. Please refer their doc [Migration Guide](https://docs.pydantic.dev/latest/migration/ ). Some of the breaking changes include `Optional[type]` no longer has a default value `None` unless given explicitly.

**Comment by necaris** [comment]
@mak626 @abhinand-c sounds like we will need a new major version & branch to support both. Would you be willing to open a PR from your test release?

**Comment by abhinand-c** [comment]
@necaris Sure, will open a PR soon.
