### ISSUE TITLE
Restore Graphene 2 support?

### ISSUE THREAD

**Issue by nick-merrill** [graphql-python/graphene-pydantic#92]
I added a comment to an already-merged PR, so creating an issue to keep track of this question.

https://github.com/graphql-python/graphene-pydantic/commit/b0430316c2fedbe45a2a36cf534e7e1cc5dad3cd#r127675726

> Is dropping support for Graphene 2 intentional? It looked like there was a decision to specifically support Graphene 2 in 2022: #77 
>
> It looks like version 0.4.0 on PyPi supports Graphene 2, but version 0.4.1 does not, and I think it may be due to this change.
>
> Sorry if I'm missing a deliberate choice to drop Graphene 2 support. Thanks!

**Comment by necaris** [comment]
@nick-merrill thanks for raising this -- with 0.4.2, support should be restored. See #93 for the PR.
